import { ReactNode } from 'react';

export const metadata = {
  title: 'Welcome to css-module-reprex',
  description: 'Generated by create-nx-workspace',
  metadataBase: `https://${process.env['NEXT_PUBLIC_APP_URL']}`,
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
